### ISSUE TITLE
Related paper of this repository.

### ISSUE THREAD

**Issue by leekwoon** [alexunderch/ASR_probing#6]
Hi, Are there any paper related to this repo?

**Comment by alexunderch** [comment]
Hey! Unfortunately, due to some circumstances, this project was abandoned due to no interest of senior researchers at MIPT, so nothing but an overleaf template in Readme. However, this line of work has been continued [here](https://github.com/AIRI-Institute/Probing_framework), without me. There was a paper, I guess! Thank you for the interest.

**Comment by leekwoon** [comment]
Thanks for your answer!
